import { Header } from 'components/header'
import { Wrapper } from 'components/wrapper'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
        <main></main>
      </Wrapper>
    </>
  )
}
